<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = now();

        Category::insert([
            [
                'id' => 0,
                'name' => 'Điện thoại',
                'slug' => 'dien-thoai',
                'icon' => null,
                'parent_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 1,
                'name' => 'Máy tính bảng',
                'slug' => 'may-tinh-bang',
                'icon' => null,
                'parent_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'name' => 'Laptop',
                'slug' => 'laptop',
                'icon' => null,
                'parent_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'name' => 'TV & Màn hình',
                'slug' => 'tv-va-man-hinh',
                'icon' => null,
                'parent_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'name' => 'Phụ kiện',
                'slug' => 'phu-kien',
                'icon' => null,
                'parent_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 5,
                'name' => 'iPhone',
                'slug' => 'iphone',
                'icon' => 'https://iconape.com/wp-content/files/qd/17570/svg/cib-apple-logo-icon-png-svg.png',
                'parent_id' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 6,
                'name' => 'Samsung',
                'slug' => 'samsung',
                'icon' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Samsung_Logo.svg/2560px-Samsung_Logo.svg.png',
                'parent_id' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 7,
                'name' => 'Xiaomi',
                'slug' => 'xiaomi',
                'icon' => 'https://www.freepnglogos.com/uploads/xiaomi-png/xiaomi-logo-logos-marcas-8.png',
                'parent_id' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 8,
                'name' => 'Oppo',
                'slug' => 'oppo',
                'icon' => 'https://download.logo.wine/logo/Oppo/Oppo-Logo.wine.png',
                'parent_id' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 9,
                'name' => 'Vivo',
                'slug' => 'vivo',
                'icon' => 'https://logos-world.net/wp-content/uploads/2023/03/Vivo-Logo-2009.png',
                'parent_id' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 10,
                'name' => 'Sony',
                'slug' => 'sony',
                'icon' => 'https://1000logos.net/wp-content/uploads/2021/05/Sony-logo.png',
                'parent_id' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 11,
                'name' => 'HTC',
                'slug' => 'htc',
                'icon' => 'https://1000logos.net/wp-content/uploads/2017/02/Colors-HTC-Logo.jpg',
                'parent_id' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 12,
                'name' => 'Nokia',
                'slug' => 'nokia',
                'icon' => 'https://www.nokia.com/sites/default/files/styles/scale_720_not_convert_webp/public/2023-02/nokia-refreshed-logo-2_1.png',
                'parent_id' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 13,
                'name' => 'LG',
                'slug' => 'lg',
                'icon' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/LG_logo_%282014%29.svg/600px-LG_logo_%282014%29.svg.png',
                'parent_id' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 14,
                'name' => 'Huawei',
                'slug' => 'huawei',
                'icon' => 'https://cdn.iconscout.com/icon/free/png-256/free-huawei-3521494-2944938.png',
                'parent_id' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 15,
                'name' => 'Nubia',
                'slug' => 'nubia',
                'icon' => 'https://upload.wikimedia.org/wikipedia/commons/2/2d/Nubia-logo.png',
                'parent_id' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 16,
                'name' => 'Realme',
                'slug' => 'realme',
                'icon' => 'https://upload.wikimedia.org/wikipedia/commons/9/91/Realme_logo.png',
                'parent_id' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 17,
                'name' => 'OnePlus',
                'slug' => 'oneplus',
                'icon' => 'https://cdn-icons-png.flaticon.com/512/882/882743.png',
                'parent_id' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 18,
                'name' => 'Pixel',
                'slug' => 'pixel',
                'icon' => 'https://play-lh.googleusercontent.com/Ow3BKkMIl0PrlPdr6lpyxO_ybeEgiBCpDQl8vMZK0gCmMM8XyUqP4PmVjeMx0pgx5wU',
                'parent_id' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 19,
                'name' => 'Redmi',
                'slug' => 'redmi',
                'icon' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Redmi_Logo.svg/2560px-Redmi_Logo.svg.png',
                'parent_id' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 20,
                'name' => 'Ipad',
                'slug' => 'ipad',
                'icon' => 'https://iconape.com/wp-content/files/qd/17570/svg/cib-apple-logo-icon-png-svg.png',
                'parent_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 21,
                'name' => 'Samsung',
                'slug' => 'samsung',
                'icon' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Samsung_Logo.svg/2560px-Samsung_Logo.svg.png',
                'parent_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 22,
                'name' => 'Redmi',
                'slug' => 'redmi',
                'icon' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Redmi_Logo.svg/2560px-Redmi_Logo.svg.png',
                'parent_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 23,
                'name' => 'Huawei',
                'slug' => 'huawei',
                'icon' => 'https://cdn.iconscout.com/icon/free/png-256/free-huawei-3521494-2944938.png',
                'parent_id' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 24,
                'name' => 'Macbook',
                'slug' => 'macbook',
                'icon' => 'https://iconape.com/wp-content/files/qd/17570/svg/cib-apple-logo-icon-png-svg.png',
                'parent_id' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 25,
                'name' => 'Surface',
                'slug' => 'surface',
                'icon' => 'https://static-00.iconduck.com/assets.00/microsoft-icon-2048x2048-xtoxrveo.png',
                'parent_id' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 26,
                'name' => 'Asus',
                'slug' => 'asus',
                'icon' => 'https://cdn-icons-png.flaticon.com/512/882/882744.png',
                'parent_id' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 27,
                'name' => 'Lenovo',
                'slug' => 'lenovo',
                'icon' => 'https://w7.pngwing.com/pngs/631/322/png-transparent-lenovo-logo-laptop-lenovo-thinkpad-thinkpad-x1-carbon-intel-dell-lenovo-logo-electronics-text-rectangle.png',
                'parent_id' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 28,
                'name' => 'Dell',
                'slug' => 'dell',
                'icon' => 'https://upload.wikimedia.org/wikipedia/commons/2/25/Dell_logo.png',
                'parent_id' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 29,
                'name' => 'HP',
                'slug' => 'hp',
                'icon' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/HP_logo_2012.svg/2048px-HP_logo_2012.svg.png',
                'parent_id' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 30,
                'name' => 'Acer',
                'slug' => 'acer',
                'icon' => 'https://cdn-icons-png.flaticon.com/512/882/882748.png',
                'parent_id' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 31,
                'name' => 'MSI',
                'slug' => 'msi',
                'icon' => 'https://cdn.iconscout.com/icon/free/png-256/free-msi-282303.png',
                'parent_id' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 32,
                'name' => 'Samsung',
                'slug' => 'samsung',
                'icon' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Samsung_Logo.svg/2560px-Samsung_Logo.svg.png',
                'parent_id' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 33,
                'name' => 'Thinkpad',
                'slug' => 'thinkpad',
                'icon' => 'https://e7.pngegg.com/pngimages/360/3/png-clipart-thinkpad-logo-thinkpad-x-series-laptop-thinkpad-e-series-lenovo-pointing-stick-lenovo-logo-electronics-text.png',
                'parent_id' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 34,
                'name' => 'Samsung',
                'slug' => 'samsung',
                'icon' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Samsung_Logo.svg/2560px-Samsung_Logo.svg.png',
                'parent_id' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 35,
                'name' => 'LG',
                'slug' => 'lg',
                'icon' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/LG_logo_%282014%29.svg/600px-LG_logo_%282014%29.svg.png',
                'parent_id' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 36,
                'name' => 'Sony',
                'slug' => 'sony',
                'icon' => 'https://1000logos.net/wp-content/uploads/2021/05/Sony-logo.png',
                'parent_id' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 37,
                'name' => 'TCL',
                'slug' => 'tcl',
                'icon' => 'https://iconape.com/wp-content/png_logo_vector/tcl.png',
                'parent_id' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 38,
                'name' => 'Panasonic',
                'slug' => 'panasonic',
                'icon' => 'https://static.vecteezy.com/system/resources/previews/012/871/380/non_2x/panasonic-brand-icon-illustration-top-tech-company-logotype-free-png.png',
                'parent_id' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 39,
                'name' => 'Philips',
                'slug' => 'philips',
                'icon' => 'https://cdn-icons-png.flaticon.com/512/882/882703.png',
                'parent_id' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 40,
                'name' => 'Sharp',
                'slug' => 'sharp',
                'icon' => 'https://cdn-icons-png.flaticon.com/512/882/882714.png',
                'parent_id' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 41,
                'name' => 'Asanzo',
                'slug' => 'asanzo',
                'icon' => 'https://bizweb.dktcdn.net/100/441/580/themes/841444/assets/logo.png?1717733146728',
                'parent_id' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 42,
                'name' => 'Xiaomi',
                'slug' => 'xiaomi',
                'icon' => 'https://www.freepnglogos.com/uploads/xiaomi-png/xiaomi-logo-logos-marcas-8.png',
                'parent_id' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 43,
                'name' => 'LG',
                'slug' => 'lg',
                'icon' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/LG_logo_%282014%29.svg/600px-LG_logo_%282014%29.svg.png',
                'parent_id' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 44,
                'name' => 'Apple',
                'slug' => 'apple',
                'icon' => 'https://iconape.com/wp-content/files/qd/17570/svg/cib-apple-logo-icon-png-svg.png',
                'parent_id' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 45,
                'name' => 'Hoco',
                'slug' => 'hoco',
                'icon' => 'https://i0.wp.com/www.hoco-algerie.com/wp-content/uploads/2021/12/Hoco-LOGO.png?fit=225%2C225&ssl=1',
                'parent_id' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 46,
                'name' => 'Baseus',
                'slug' => 'baseus',
                'icon' => 'https://asset.brandfetch.io/idKP0ip8J0/idrE1vy4R3.jpeg',
                'parent_id' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 47,
                'name' => 'Remax',
                'slug' => 'remax',
                'icon' => 'https://img.icons8.com/?size=512&id=fCtvaTDdAVMD&format=png',
                'parent_id' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 48,
                'name' => 'Anker',
                'slug' => 'anker',
                'icon' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Anker-logo.svg/1280px-Anker-logo.svg.png',
                'parent_id' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 49,
                'name' => 'Xiaomi',
                'slug' => 'xiaomi',
                'icon' => 'https://www.freepnglogos.com/uploads/xiaomi-png/xiaomi-logo-logos-marcas-8.png',
                'parent_id' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 50,
                'name' => 'Samsung',
                'slug' => 'samsung',
                'icon' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Samsung_Logo.svg/2560px-Samsung_Logo.svg.png',
                'parent_id' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 51,
                'name' => 'Apple',
                'slug' => 'apple',
                'icon' => 'https://iconape.com/wp-content/files/qd/17570/svg/cib-apple-logo-icon-png-svg.png',
                'parent_id' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 52,
                'name' => 'Sony',
                'slug' => 'sony',
                'icon' => 'https://1000logos.net/wp-content/uploads/2021/05/Sony-logo.png',
                'parent_id' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 53,
                'name' => 'JBL',
                'slug' => 'jbl',
                'icon' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/JBL_logo.svg/2500px-JBL_logo.svg.png',
                'parent_id' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 54,
                'name' => 'Bose',
                'slug' => 'bose',
                'icon' => 'https://1000logos.net/wp-content/uploads/2021/05/Bose-logo.png',
                'parent_id' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 55,
                'name' => 'Beats',
                'slug' => 'beats',
                'icon' => 'https://seeklogo.com/images/B/beats-logo-6D586C8DEB-seeklogo.com.png',
                'parent_id' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 56,
                'name' => 'Sennheiser',
                'slug' => 'sennheiser',
                'icon' => 'https://1000logos.net/wp-content/uploads/2021/05/Sennheiser-logo.png',
                'parent_id' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
